# Generated by Django 3.1.7 on 2021-03-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('published_time',), 'verbose_name_plural': 'stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(unique_for_date='published_time', verbose_name='slug'),
        ),
    ]
