# Generated by Django 3.1.6 on 2021-02-19 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('key', models.CharField(max_length=40)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='creation timestamp')),
                ('purpose', models.CharField(choices=[('B', 'Blocked'), ('S', 'Sign Up'), ('R', 'Reset Pwd'), ('C', 'Cancel Account'), ('E', 'Change E-Mail')], max_length=1)),
                ('notifications', models.SmallIntegerField(default=0, help_text='homw many times has been notified', verbose_name='notifications counter')),
            ],
        ),
    ]
